#pragma once

#include "MGMTErrorCode.hpp"

enum class                  MGMTCommandCode : uint16_t
{
    MGMTReadManagementVersionInformationCommand = 0x01,
    MGMTReadManagementSupportedCommandsCommand,
    MGMTReadControllerIndexListCommand,
    MGMTReadControllerInformationCommand,
    MGMTSetPoweredCommand,
    MGMTSetDiscoverableCommand,
    MGMTSetConnectableCommand,
    MGMTSetFastConnectableCommand,
    MGMTSetBondableCommand,
    MGMTSetLinkSecurityCommand,
    MGMTSetSecureSimplePairingCommand,
    MGMTSetHighSpeedCommand,
    MGMTSetLowEnergyCommand,
    MGMTSetDeviceClass,
    MGMTSetLocalNameCommand,
    MGMTAddUUIDCommand,
    MGMTRemoveUUIDCommand,
    MGMTLoadLinkKeysCommand,
    MGMTLoadLongTermKeysCommand,
    MGMTDisconnectCommand,
    MGMTGetConnectionsCommand,
    MGMTPINCodeReplyCommand,
    MGMTPINCodeNegativeReplyCommand,
    MGMTSetIOCapabilityCommand,
    MGMTPairDeviceCommand,
    MGMTCancelPairDeviceCommand,
    MGMTUnpairDeviceCommand,
    MGMTUserConfirmationReplyCommand,
    MGMTUserConfirmationNegativeReplyCommand,
    MGMTUserPasskeyReplyCommand,
    MGMTUserPasskeyNegativeReplyCommand,
    MGMTReadLocalOutOfBandDataCommand,
    MGMTAddRemoteOutOfBandDataCommand,
    MGMTRemoveRemoteOutOfBandDataCommand,
    MGMTStartDiscoveryCommand,
    MGMTStopDiscoveryCommand,
    MGMTConfirmNameCommand,
    MGMTBlockDeviceCommand,
    MGMTUnblockDeviceCommand,
    MGMTSetDeviceIDCommand,
    MGMTSetAdvertisingCommand,
    MGMTEDRCommand,
    MGMTSetStaticAddressCommand,
    MGMTSetScanParametersCommand,
    MGMTSetSecureConnectionsCommand,
    MGMTSetDebugKeysCommand,
    MGMTSetPrivacyCommand,
    MGMTLoadIdentityResolvingKeysCommand,
    MGMTGetConnectionInformationCommand,
    MGMTGetClockInformationCommand,
    MGMTAddDeviceCommand,
    MGMTRemoveDeviceCommand,
    MGMTLoadConnectionParametersCommand,
    MGMTReadUnconfiguredControllerIndexListCommand,
    MGMTReadControllerConfigurationInformationCommand,
    MGMTSetExternalConfigurationCommand,
    MGMTSetPublicAddressCommand,
    MGMTStartServiceDiscoveryCommand,
    MGMTReadLocalOutOfBandExtendedDataCommand,
    MGMTReadExtendedControllerIndexListCommand,
    MGMTReadAdvertisingFeaturesCommand,
    MGMTAddAdvertisingCommand,
    MGMTRemoveAdvertisingCommand,
    MGMTGetAdvertisingSizeInformationCommand,
    MGMTStartLimitedDiscoveryCommand,
    MGMTReadExtendedControllerInformationCommand,
    MGMTSetAppearanceCommand,
};

struct __attribute__((packed))  MGMTCommandPacket
{
    const MGMTCommandCode       commandCode;
    uint16_t                    controllerIndex;
    uint16_t                    parameterLength;
};